"""
Generate the public stand-in Catalogue file, by sampling the Lab space.

    python tools/generate_stand_in_catalogue.py            # write the file
    python tools/generate_stand_in_catalogue.py --check     # verify the committed file matches

The Catalogue this project ships against is Arun Paint Industries' measured values, which have not
arrived yet. Everything downstream — search, Shade Family browsing, and above all the claim that a
thousand-plus Shade Catalogue scrolls smoothly — needs a file of realistic size today.

Why generated rather than borrowed: a real manufacturer's fandeck is their data, and committing one
would put a redistribution question in the repository for values we are going to replace anyway.
Sampling the Lab space ourselves has no licence, and gives something better for testing: Shades
spread evenly across the families a dealer browses, at a size we choose.

What this is *not* is accurate. These are plausible paint colours, not measured ones. Accuracy
evaluation waits for the real data — see docs/design-decisions.md §7.

Deterministic: no randomness anywhere, so the same input always produces byte-identical output and
`--check` is meaningful in CI.
"""

import argparse
import json
import math
import sys
from pathlib import Path

CATALOGUE_ID = "public-stand-in"
CATALOGUE_NAME = "Public stand-in Catalogue"
VERSION = "2026-08-19"
SOURCE = "Generated by tools/generate_stand_in_catalogue.py — sampled Lab values, not measured."

DATA_DIR = Path(__file__).resolve().parent.parent / "data" / "catalogue"
OUTPUT_PATH = DATA_DIR / f"{CATALOGUE_ID}-{VERSION}.json"

# The Shade Families a Dealer browses, each with the region of Lab it occupies.
#
# Sampling is done in cylindrical Lab (lightness, chroma, hue angle) rather than in a and b
# directly, because that is how paint ranges are actually laid out: a family is one hue band shown
# at many lightnesses and strengths. Sampling a and b on a grid instead would put most of the
# results in colours no manufacturer sells.
#
# Tuned to look like a fandeck, so these constants live here together rather than inline
# (conventions.md §4): paint skews light and unsaturated, so lightness runs high and chroma stays
# well below what the space allows.
FAMILIES = (
    # name, hue angle degrees (start, end), lightness (min, max), chroma (min, max), rows, columns
    ("Whites", (60, 100), (91, 97), (1, 6), 8, 12),
    ("Neutrals", (55, 95), (72, 92), (2, 11), 9, 12),
    ("Greys", (200, 280), (38, 88), (0, 5), 10, 10),
    ("Earth Tones", (40, 75), (34, 78), (8, 26), 9, 11),
    ("Terracottas", (25, 45), (32, 72), (14, 38), 8, 10),
    ("Reds", (5, 30), (26, 66), (18, 52), 8, 10),
    ("Pinks", (350, 20), (58, 88), (8, 32), 8, 10),
    ("Oranges", (35, 60), (52, 82), (20, 52), 7, 10),
    ("Yellows", (75, 100), (68, 92), (14, 54), 8, 11),
    ("Greens", (110, 160), (36, 82), (8, 38), 9, 11),
    ("Teals", (170, 210), (38, 80), (6, 30), 8, 10),
    ("Blues", (215, 270), (32, 80), (6, 34), 9, 11),
    ("Violets", (285, 330), (34, 78), (8, 32), 8, 10),
)

# Names are built from a family's own vocabulary, so a Shade reads like something a dealer would say
# out loud rather than like a coordinate. Modifier and noun are indexed off the Shade's serial,
# which makes every name within a family distinct: a name search that returned three identical
# labels would read as a bug in the search rather than a quirk of the fixture. Twelve modifiers
# times twelve nouns is 144 combinations per family, comfortably above the largest family below.
MODIFIERS = (
    "Morning",
    "Quiet",
    "Soft",
    "Deep",
    "Antique",
    "Winter",
    "Summer",
    "Faded",
    "Rich",
    "Pale",
    "Old",
    "Still",
)

NOUNS = {
    "Whites": (
        "Linen",
        "Chalk",
        "Cotton",
        "Porcelain",
        "Bone",
        "Cloud",
        "Paper",
        "Salt",
        "Milk",
        "Ivory",
        "Lace",
        "Plaster",
    ),
    "Neutrals": (
        "Oat",
        "Almond",
        "Parchment",
        "Sand",
        "Straw",
        "Putty",
        "Canvas",
        "Wheat",
        "Biscuit",
        "Jute",
        "Muslin",
        "Barley",
    ),
    "Greys": (
        "Slate",
        "Ash",
        "Pewter",
        "Flint",
        "Smoke",
        "Granite",
        "Iron",
        "Shadow",
        "Graphite",
        "Basalt",
        "Zinc",
        "Gravel",
    ),
    "Earth Tones": (
        "Ochre",
        "Umber",
        "Clay",
        "Loam",
        "Bark",
        "Walnut",
        "Hessian",
        "Tobacco",
        "Chestnut",
        "Peat",
        "Cocoa",
        "Driftwood",
    ),
    "Terracottas": (
        "Brick",
        "Tile",
        "Rust",
        "Amber",
        "Ember",
        "Copper",
        "Henna",
        "Sienna",
        "Kiln",
        "Clove",
        "Paprika",
        "Bronze",
    ),
    "Reds": (
        "Garnet",
        "Cherry",
        "Lacquer",
        "Chilli",
        "Claret",
        "Vermilion",
        "Ruby",
        "Carmine",
        "Pomegranate",
        "Sindoor",
        "Crimson",
        "Madder",
    ),
    "Pinks": (
        "Rose",
        "Blush",
        "Petal",
        "Coral",
        "Peony",
        "Dusk",
        "Shell",
        "Camellia",
        "Guava",
        "Ballet",
        "Quartz",
        "Bougainvillea",
    ),
    "Oranges": (
        "Marigold",
        "Apricot",
        "Saffron",
        "Tangerine",
        "Papaya",
        "Flame",
        "Peach",
        "Zest",
        "Nasturtium",
        "Melon",
        "Persimmon",
        "Cinnamon",
    ),
    "Yellows": (
        "Turmeric",
        "Mustard",
        "Honey",
        "Corn",
        "Lemon",
        "Butter",
        "Sunflower",
        "Bamboo",
        "Ghee",
        "Chamomile",
        "Custard",
        "Millet",
    ),
    "Greens": (
        "Moss",
        "Olive",
        "Fern",
        "Sage",
        "Basil",
        "Cypress",
        "Meadow",
        "Jade",
        "Pistachio",
        "Neem",
        "Bottle",
        "Celadon",
    ),
    "Teals": (
        "Lagoon",
        "Verdigris",
        "Peacock",
        "Cove",
        "Mineral",
        "Tide",
        "Kingfisher",
        "Reef",
        "Aqua",
        "Estuary",
        "Cyan",
        "Seagrass",
    ),
    "Blues": (
        "Indigo",
        "Cobalt",
        "Denim",
        "Harbour",
        "Sapphire",
        "Monsoon",
        "Ink",
        "Cerulean",
        "Azure",
        "Delft",
        "Midnight",
        "Steel",
    ),
    "Violets": (
        "Iris",
        "Plum",
        "Lilac",
        "Orchid",
        "Mulberry",
        "Aubergine",
        "Heather",
        "Damson",
        "Amethyst",
        "Thistle",
        "Wine",
        "Grape",
    ),
}

# Finish is Catalogue metadata only in V1 (design-decisions.md §8). Which finishes a Shade is sold
# in varies in real ranges, so it varies here too — a UI that only ever sees the same three would
# not prove it renders the field at all.
FINISH_SETS = (
    ("matte", "satin"),
    ("matte", "satin", "gloss"),
    ("satin",),
    ("matte",),
    ("satin", "gloss"),
)

# Shade Codes carry the family in their leading digits, which is what a real fandeck does — the
# Dealer learns that the 4000s are the earth tones.
CODE_PREFIX = "PS"


def _span(start: float, end: float, steps: int) -> list[float]:
    """`steps` evenly spaced values from start to end inclusive. One step returns the midpoint."""

    if steps == 1:
        return [(start + end) / 2]
    stride = (end - start) / (steps - 1)
    return [start + stride * index for index in range(steps)]


def _hue_span(start_degrees: float, end_degrees: float, steps: int) -> list[float]:
    """Hue angles across a band, taking the short way round when the band crosses 0°.

    Pinks sit either side of 0° (350° to 20°), so treating the band as a plain numeric range would
    walk the long way through every other hue in the wheel.
    """

    if end_degrees < start_degrees:
        end_degrees += 360
    return [angle % 360 for angle in _span(start_degrees, end_degrees, steps)]


def build_shades() -> list[dict]:
    shades: list[dict] = []

    for family_index, (family, hues, lightness, chroma, rows, columns) in enumerate(FAMILIES, 1):
        nouns = NOUNS[family]
        serial = 0

        # Lightness down the rows, hue and strength across the columns: one page of a fandeck.
        for lightness_value in _span(lightness[1], lightness[0], rows):
            hue_angles = _hue_span(hues[0], hues[1], columns)
            chromas = _span(chroma[0], chroma[1], columns)

            for column in range(columns):
                serial += 1
                hue_radians = math.radians(hue_angles[column])
                chroma_value = chromas[column]

                # A dark shade cannot also be weak and still read as its family, and a very light
                # one cannot be strong — pale colours are pale because there is little pigment.
                # Scaling chroma by lightness is what keeps the extremes of each page believable.
                chroma_value *= 0.55 + 0.45 * (lightness_value / 100)

                shades.append(
                    {
                        "shade_code": f"{CODE_PREFIX}-{family_index * 1000 + serial}",
                        "name": f"{MODIFIERS[(serial - 1) // len(nouns) % len(MODIFIERS)]} "
                        f"{nouns[(serial - 1) % len(nouns)]}",
                        "shade_family": family,
                        "lab": {
                            "l": round(lightness_value, 2),
                            "a": round(chroma_value * math.cos(hue_radians), 2),
                            "b": round(chroma_value * math.sin(hue_radians), 2),
                        },
                        "finishes": list(FINISH_SETS[serial % len(FINISH_SETS)]),
                    }
                )

    return shades


def build_catalogue() -> dict:
    shades = build_shades()

    # A duplicate Shade Code would be a silent fault: the loader treats the code as unique, so two
    # rows sharing one would make a Shade unreachable rather than error.
    codes = [shade["shade_code"] for shade in shades]
    duplicates = {code for code in codes if codes.count(code) > 1}
    if duplicates:
        raise SystemExit(f"generated duplicate Shade Codes: {sorted(duplicates)}")

    # Names are not required to be unique by the format, but a fixture with repeats would make a
    # name search look broken, so the generator holds itself to a higher standard than the loader.
    names = [shade["name"] for shade in shades]
    repeated = {name for name in names if names.count(name) > 1}
    if repeated:
        raise SystemExit(f"generated duplicate Shade names: {sorted(repeated)}")

    return {
        "catalogue_id": CATALOGUE_ID,
        "catalogue_name": CATALOGUE_NAME,
        "version": VERSION,
        "source": SOURCE,
        "colour_space": {"space": "CIELAB", "reference_white": "D65", "observer": "2"},
        "shades": shades,
    }


def serialise(catalogue: dict) -> str:
    # Newline-terminated, LF, two-space indent: a text file that behaves the same on both platforms
    # and produces a readable diff when the generator is retuned.
    return json.dumps(catalogue, indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed file matches what this script generates; write nothing",
    )
    arguments = parser.parse_args()

    expected = serialise(build_catalogue())

    if arguments.check:
        if not OUTPUT_PATH.exists():
            raise SystemExit(f"{OUTPUT_PATH} is missing. Run this script without --check.")
        if OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                f"{OUTPUT_PATH} does not match the generator. "
                "Re-run this script without --check and commit the result."
            )
        print(f"{OUTPUT_PATH.name} matches the generator.")
        return

    OUTPUT_PATH.write_text(expected, encoding="utf-8", newline="\n")
    count = expected.count('"shade_code"')
    print(f"Wrote {count} Shades to {OUTPUT_PATH}", file=sys.stderr)


if __name__ == "__main__":
    main()
